### ISSUE TITLE
Очная сдача

### ISSUE THREAD

**Issue by coursar** [greatschemer/filter-map-reduce#7]
Эту задачу надо было сдавать очно. Если хотите сдавать так, то мне нужны ответы на три вопроса:
1. Какие две разновидности `reduce` применяются? Когда и почему?
2. Как отладить функции-однострочники (присылайте скриншоты) - как попасть внутрь
3. Как работает 9.4 нужно объяснить по шагам в картинках

Если сможете - ок, нет - тогда и разговора нет.

**Comment by greatschemer** [comment]
Если initialValue (аккумулятор) на первой итерации должен отличаться от первого элемента набора, то в таком случае его необходимо указать принудительно вторым параметром. 
Другой вариант, когда не важно первое значение (например, когда считаем сумму всех элементов в наборе), то initialValue можно опустить.

**Comment by greatschemer** [comment]
![Снимок экрана 2020-02-07 в 16 36 02](https://user-images.githubusercontent.com/5336802/74026419-fcfd4e00-49c7-11ea-9065-c3db8492ccbd.png)
Здесь я поставил брекпойнт в функцию-однострочник

**Comment by greatschemer** [comment]
Задачу 9.4 я разбил на 2 подзадачи. 
В первой я получаю список односложный список с тратами:
`function getStatByCategories(purchases) {
        return purchases.map(purchase => purchase.values).flat()
        .reduce((acc, currentValue) => {
            const index = acc.findIndex(i => i.category === currentValue.category);
            if (index >= 0) {
                acc[index].amount += currentValue.amount;
                return acc;
            }
            return [...acc, currentValue];
        }, []);
    } `
Во второй я передаю этот список и на выходе получаю категорию с максимальными тратами по суммарной стоимости:
`function getCategoryWithMaxPurchases(statByCategories) {
        return statByCategories.reduce((acc, currentValue) => currentValue.amount > acc.amount ? currentValue : acc )['category'];
    }`
